version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    user: root
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    ulimits:
      nproc: 65535            # 设置线程数限制
      nofile:
        soft: 20000           # 设置文件描述符的软限制
        hard: 40000           # 设置文件描述符的硬限制
    privileged: true          # 以特权模式运行容器
    environment:
      - QDRANT__SERVICE__BIND_PORT=6333
    restart: unless-stopped
   # healthcheck:
   #   test: ["CMD-SHELL", "curl -s http://localhost:6333/metrics | grep -q 'app_status_recovery_mode 0' || exit 1"]
   #   interval: 30s  # 每隔30秒执行一次健康检查
   #   timeout: 10s   # 如果健康检查在10秒内没有响应，则视为失败
   #   retries: 3     # 如果连续3次健康检查失败，则认为服务不健康
   #   start_period: 10s  # 在容器启动后的10秒内，延迟执行第一次健康检查
  mem0:
    image: mem0:0.1
    container_name: mem0
    privileged: true
    env_file:
      - .env
    ports:
      - "5002:5000"
   # depends_on:
   #   qdrant:
   #     condition: service_healthy
    environment:
      FLASK_ENV: development